import React from "react";
import styled from "styled-components";

interface IProps {
  badgeListNum: number;
}

const MypageBadgeGauge = ({ badgeListNum }: IProps) => {
  const collectionRate = (badgeListNum ?? 0) / 36;

  const getPercent = () => {
    return collectionRate * 100;
  };
  return (
    <StyledDiv percent={getPercent()}>
      <div>
        <span>{Math.round(getPercent()) + "%"}</span>
      </div>
    </StyledDiv>
  );
};

const StyledDiv = styled.div<{ percent: number }>`
  width: 100%;
  height: 40px;
  border-radius: 20px;
  background-color: ${({ theme }) => theme.colors.brandColors.basaltGray[200]};
  overflow: hidden;
  position: relative;

  & > div {
    -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    background-color: ${({ theme }) => theme.colors.green};
    width: ${({ percent }) => percent + "%"};
    height: 100%;
    border-radius: 20px;
    display: flex;
    align-items: center;
    ${({ theme }) => theme.shadow};

    & > span {
      position: absolute;
      color: ${({ theme }) => theme.colors.brandColors.basaltGray[50]};
      font: ${({ theme }) => theme.fonts.subContentBold};
      position: absolute;
      right: 32px;
      ${({ percent }) => (percent < 30 ? "left : 32px;" : undefined)}
    }
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-2-15 9:43:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @-webkit-keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
`;

export default MypageBadgeGauge;
